### ISSUE TITLE
Matching inside string

### ISSUE THREAD

**Issue by lervag** [andymass/vim-matchup#10]
I am not sure how I think about this myself, but: With the old matchit/matchparen I would get highlighting of parentheses inside strings. This was particularly useful when writing `v:val`-type strings in vimscript.

Do you think something like this could be possible to support from vim-matchup? My initial thought is that this needs some special attention, and in particular, that it might need a customized engine. That is, when inside strings, one should use a different set of regexes and similar, in order to prevent what is inside the strings from affecting what is outside the strings.

In any case, here is an example:

```vim
let output = filter(list, "matchstr(v:val, '^\s*\zsfoo\ze\(bar\|baz\)')")
```

**Comment by andymass** [comment]
As you know, match{it,paren,-up} rely on vim's syntax highlighting to determine if it is inside strings.  If possible, I would prefer to keep that (as opposed to writing a custom parser).  So your example is wrong because vim's syntax highlighting fails on the parentheses inside the string.  Did you pick that example on purpose?
```vim
    let output = filter(list, "matchstr(v:val, '^\s*\zsfoo\ze\\(bar\\|baz\\)')")
```
A few observations:
- For me, matchparen does not work at all within strings (although the source code seems to imply that it might).
- matchit does work inside strings but fails on things like
```vim       
let z =  (   '( ' ) . ' )'
```
- vim's default `%` does not care about strings at all.  It has only one special case:
```
							*cpo-M*
	M	When excluded, "%" matching will take backslashes into
		account.  Thus in "( \( )" and "\( ( \)" the outer
		parenthesis match.  When included "%" ignores
		backslashes, which is Vi compatible.
```

Anyway, I agree it would be a nice feature and would improve compatibility.  Here is my proposal:
- use existing syntax/skip expression to determine if "skipped" or "not skipped."
- things in "skipped" highlight other things in "skipped" but nothing else.
- bonus points for future work (i.e., not right away): intelligently match comments/comments and strings/strings.

The only tricky part is motions/text-objects, but similar logic should apply.

**Comment by lervag** [comment]
Sorry, the example was not perfect. Here is a modified version:

```vim
let output = filter(list, 'matchstr(v:val, ''^\s*\zsfoo\ze\(bar\|baz\)'')')
```

The point is: With `matchparen`, when enabled, if my cursor is on the first `(` after `matchstr`, then the corresponding `)` is highlighted. This is not the case with `matchup`.

And yes, I agree that `matchit` and `matchparen` does not perfectly handle strings and comments. However, I did rely on being able to matchup (pun intended) the parantheses inside strings with matchparen, and it would make me happy if vim-matchup could do the same.

In my first post I rambled a bit with ideas on how to do this and what one should think about, but it might be that your ideas are better. In the end, the goal would be to reliably show matching parantheses also within strings and comments, if this is possible.

**Comment by andymass** [comment]
This change seems to work.  Highlighting is as you expect- something inside strings/comments will never match something outside.  Although, for example, something in a string can still match something in a comment, there is just "skipped" and "not skipped."

For motions, I had to make a compromise.  If the cursor is in a "skipped" region, the motions will move to anything, regardless of inside comments or strings.  If the cursor is in normal code, comments and strings are ignored.

**Comment by lervag** [comment]
Agreed, this seems to work well. Thanks!
