### ISSUE TITLE
DoMatchParen not working

### ISSUE THREAD

**Issue by Trid-collab** [andymass/vim-matchup#193]
I am using latest neovim nightly 0.6 with tokyonight colorscheme without any additional config. I find the matching parenthesis are not being highlighted as it happens in the default neovim with the plugin.

I get it working when I put something like the following in the init.vim `cmd([[au VimEnter * highlight MatchParen ctermbg=blue guibg=lightblue]])
`

Am I missing something here

**Comment by andymass** [comment]
So the problem is the default colorscheme makes the matching invisible for some reason? 

What does `:verb hi MatchParen` say?

What is wrong with the workaround?

**Comment by andymass** [comment]
Most likely, the problem is caused by the tokyonight colorscheme on terminals that do not support bold or underlines.

https://github.com/ghifarit53/tokyonight-vim/blob/ea68b37bff60104e71ed50fc37fa8f8ac53b727d/colors/tokyonight.vim#L1678

One may configure each highlight group as necessary, for instance.

    hi MatchParen guifg=#7AA2F7
    hi MatchParenCur guifg=#7AA2F7
    hi MatchWord guifg=#7AA2F7
    hi MatchWordCur guifg=#7AA2F7

MatchParen: matching symbols (parens, brackets, etc).  MatchParenCur: current cursor symbol (when matched).

MatchWord: matching words.  MatchWordCur: current cursor word (when matched).
