### ISSUE TITLE
Non-TSX TypeScript

### ISSUE THREAD

**Issue by samhh** [andymass/vim-matchup#194]
Hi there! Angle brackets don't appear to match in `typescript` (`.ts`), but work fine in `typescriptreact` (`.tsx`). I suspect it's falling back to vanilla Vim matching.

Neovim 0.5.1, Treesitter integration disabled (enabled is worse, but that's probably unrelated).

**Comment by andymass** [comment]
I am not sure why but it looks like the typescript filetype does not define any match words.  You can lift them from typescriptreact.vim: 

Put in your ftplugin/typescript.vim file:
```
if exists("loaded_matchit")
    let b:match_ignorecase = 0
    let b:match_words = s:match_words .
		\	'<:>,' .
		\	'<\@<=\([^ \t>/]\+\)\%(\s\+[^>]*\%([^/]>\|$\)\|>\|$\):<\@<=/\1>,' .
		\	'<\@<=\%([^ \t>/]\+\)\%(\s\+[^/>]*\|$\):/>'
endif
```

Regarding vanilla vim matching, should not be the case since when vim-matchup is installed there should be no other matching active.

**Comment by samhh** [comment]
That fixes it for me, thanks!
