### ISSUE TITLE
wrong if/end

### ISSUE THREAD

**Issue by Shane-XB-Qian** [andymass/vim-matchup#214]
```vim
let foo = {'end': 123}

if 123
	echo (foo.end)
else
	echo 'bar'
endif
```

the `if` matched that `end` of `foo.end`, but not the `endif` (and `else`).
// vim 8.2.4602

**Comment by andymass** [comment]
Is this a recent regression?  I cannot seem to reproduce it, I get the correct matching when I enter the example in a file called `foo.vim`.

**Comment by Shane-XB-Qian** [comment]
ok, i noticed that seems correct if set rtp only to matchup.
but no idea where made it difference:
not sure what's this: `matchup#util#check_match_words('9071a9a')` meant in your code, but it returns 'false' in my case,
do you know where would make this happen?

**Comment by andymass** [comment]
I almost understand the issue but it is difficult to fix.  `check_match_words` ensures that if the user has modified their match_words then the default substitutions won't be performed by match-up.  This implies that either a) upstream has changed the match_words or b) you have some other plugin or vimrc configuration which modifies match_words for vim.

I am considering to remove the check_match_words, in other words apply the patches regardless of whether the user has modified match_words.  We may want to add a configuration option to prevent this.

The core issue here is that we cannot predict what initial value match_words the user will have because vim itself has changed it.

**Comment by Shane-XB-Qian** [comment]
or actually i am not very sure what happened, i just tried this 2 ways just now,
but i remember i tried to modify those too before open this ticket, not sure what changed, 
but now it is working by those 2 ways anyway.

**Comment by Shane-XB-Qian** [comment]
hello, what you decided to do now? or better user to workaround it as one of i describe at above comment?

**Comment by andymass** [comment]
I removed the block of code because it seems to cause the issue.  If other problems now appear please let me know.
