### ISSUE TITLE
Show relative line number on matchup offscreen popup

### ISSUE THREAD

**Issue by WilliamHsieh** [andymass/vim-matchup#253]
**Is your feature request related to a problem? Please describe.**
As a user who relies on relative line number setting, I always jump to the wrong position when reading the line number of the matchup offscreen popup.

**Describe the solution you'd like**
Instead of a regular line number, please consider following the user's configuration on relative line number.

**Additional context**
Since the status method is already using relative line number, I would like to have the same behaviour across methods.

**Comment by andymass** [comment]
Can you please clarify what is your platform and configuration?

**Comment by WilliamHsieh** [comment]
**platform**
fedora 36

**configuration**
This the minimal `init.lua`
```lua
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.ts = 2

local packer_path = vim.fn.stdpath "data" .. "/site/pack/packer/start/packer.nvim"
if vim.fn.empty(vim.fn.glob(packer_path)) > 0 then
  vim.fn.system { "git", "clone", "--depth", "1", "https://github.com/wbthomason/packer.nvim", packer_path }
  vim.cmd("packadd packer.nvim")
end

require("packer").startup {
  function(use)
    use {
      "andymass/vim-matchup",
      config = function()
        vim.g.matchup_matchparen_offscreen = {
          method = 'popup',
          fullwidth = 1
        }
      end
    }
  -- press <C-e> until `function(use)` is not visible, then put cursor on the following `end`
  end,
}

```

The cursor is on line 23, and the matchup offscreen popup shows line 12, which is not a relative line number.
![image](https://user-images.githubusercontent.com/23206205/196352593-2be84e1d-895a-4bfb-a918-cb8193d253ac.png)

**Comment by andymass** [comment]
Have added support for relativenumber on floating window.  Unfortunately, I don't yet know how to get both highlighting and relativenumber, so for now it will just be a plain text.

**Comment by latipun7** [comment]
> Unfortunately, I don't yet know how to get both highlighting and relativenumber, so for now it will just be a plain text.

So that's why I lost the popup syntax highlighting after updating to the latest master. I was going to open a new issue but found this. I hope there will be a solution to this.
![image](https://user-images.githubusercontent.com/20012970/205227107-f189ffe0-c309-4bb8-a2ee-db47b2573319.png)

Great plugin, thank you 🙏

**Comment by andymass** [comment]
This should be supported now:

   vim.g.matchup_matchparen_offscreen = {
          method = 'popup',
          fullwidth = 1,
          syntax_hl = 1
        }

It requires syntax_hl = 1 currently because there is a potential for worse performance.  neovim does not support relative number in popup so we have to fake it using ext marks and building them may take more time than if native rendering was possible.
