### ISSUE TITLE
Deferred timer fails when using FlyGrep

### ISSUE THREAD

**Issue by kristijanhusak** [andymass/vim-matchup#39]
### Explain the issue

After searching project with [FlyGrep.vim](https://github.com/wsdjeg/FlyGrep.vim), 
and using `let g:matchup_matchparen_deferred = 1`, i get this error:
![screenshot](https://i.imgur.com/vLsVzb0.png)
### Minimal working example

* Open any project
* run `:FlyGrep`
* find something
* press enter

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The
following should often suffice:

```vim
set nocompatible

" load match-up
let &rtp  = '~/.vim/bundle/vim-matchup,' . &rtp
let &rtp .= ',~/.vim/bundle/vim-matchup/after'

" load other plugins, if necessary
let &rtp .= '~/path/to/FlyGrep.vim'

filetype plugin indent on
syntax enable

" match-up options go here
let g:matchup_matchparen_deferred = 1
```

When `let g:matchup_matchparen_deferred = 1` is not set, everything works fine.

Note that i'm using neovim v0.3.2-dev

**Comment by andymass** [comment]
Note, this doesn't happen in vim, only neovim.  I think the reason is in neovim timers can start from 0 and in vim they start from 1.  But FlyGrep does `timer_stop` on `s:grep_timer_id` even though it can be 0 which is a valid timer:

https://github.com/wsdjeg/FlyGrep.vim/blob/82bd158ef4c1bab9a1ae442dacaf95f1b9557715/autoload/SpaceVim/plugins/flygrep.vim#L132-L135

@wsdjeg 

I think this should be fixed in either FlyGrep or neovim.

**Comment by kristijanhusak** [comment]
Ok thanks. I can't open issue on FlyGrep because they blocked it, so i guess it is what it is. Thanks.

**Comment by andymass** [comment]
I think you can post an issue in https://github.com/SpaceVim/SpaceVim/issues/.  The author is very active.
