### ISSUE TITLE
Xcode-style highlighting

### ISSUE THREAD

**Issue by arzg** [andymass/vim-matchup#52]
Hi,
I was wondering if it would be possible to implement highlighting in the style of Xcode? This would mean that the highlighted text would _not_ be unhighlighted when the cursor is not on it anymore. Instead, a configurable amount (say, 500ms default) of time passes before the highlighting goes away again. In other words, positioning the cursor on a pair would cause a brief flash, which would go away again after a moment, regardless of whether the cursor moves away or stays on the pair.

Thanks for all the hard work you’ve put into this plugin 😀

**Comment by andymass** [comment]
I added a match "fading" feature, which I think implements the behavior you describe.  I've never used Xcode, so I'm not totally sure if it's the same.  Let me know if there are any issues.

It only works when using deferred matching.  To enable the new feature, use the following options:
```vim
let g:matchup_matchparen_deferred = 1
let g:matchup_matchparen_deferred_fade_time = 450
```

Instead of having a default time, the option is just by default 0 (disabled).

**Comment by arzg** [comment]
Works perfectly, thanks!
