### ISSUE TITLE
g:matchup_matchparen_deferred_hide_delay has a hidden limit

### ISSUE THREAD

**Issue by idbrii** [andymass/vim-matchup#56]
g:matchup_matchparen_deferred_hide_delay appears to have no effect above certain values.

    let g:matchup_matchparen_status_offscreen = 0

    " Defer to improve cursor movement performance.
    if has('timers')
        let g:matchup_matchparen_deferred = 1
        let g:matchup_matchparen_deferred_show_delay = 150
        let g:matchup_matchparen_deferred_hide_delay = 100000
    endif

Set those values and open a new instance of vim.

I would expect when I put the cursor on a `(`, the highlight would appear and when I moved one line up, the highlight would disappear after 100 seconds. Instead, it disappears as if I'd set `g:matchup_matchparen_deferred_hide_delay = 100`

`g:matchup_matchparen_deferred_show_delay = 1000` does have a long delay before highlight is displayed.

I suspect I misunderstand how it's supposed to work?

VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 28 2019 23:01:56)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-1066

### Minimal example

```vim
  call one()
  call two()
```

BTW, great plugin!

**Comment by andymass** [comment]
Yeah, I think this is a misunderstanding of the variable, probably due to the sparse documentation and bad naming of the variables.  It's possible you are describing the "fade" feature:

    let g:matchup_matchparen_deferred = 1
    let g:matchup_matchparen_deferred_show_delay = 150
    " let g:matchup_matchparen_deferred_hide_delay = 700
    let g:matchup_matchparen_deferred_fade_time = 100000

But I can try to explain better what the variables mean, and I'll eventually add it to the documentation:

- `_show_delay`: how long after the cursor moves before we start checking whether the cursor is on a match or not.  So this applies to both making highlights and clearing them.

- `_hide_delay`: if the cursor has not stopped moving, we simply hide the highlight after this long because they are assumed to be stale.

- `_fade_time`: how long to persist a highlight after the cursor leaves it.

Let me know if this clears it up or if there's a feature request here.

Thanks :smile:

**Comment by idbrii** [comment]
Ah. g:matchup_matchparen_deferred_fade_time works as expected.

I was also on v0.3.0 which didn't have fade.

Thanks for the clarification!
