### ISSUE TITLE
{count}i% and {count}a% does not work as expected

### ISSUE THREAD

**Issue by krishnakumarg1984** [andymass/vim-matchup#66]
>`{count}i%` If count is greater than 1, the inside of the {count}th surrounding open-to-close block

This does not work as claimed in the `README.md` of the project.

### Vim Version
NVIM v0.4.0-dev

### Example to reproduce
Use the following vimscript as an example
```
if l:x == 1
  call one()
elseif l:x == 2
  call two()
elseif l:x == 3
  call three()
elseif l:x == 4
  call four()
elseif l:x == 5
  call five()
elseif l:x == 6
  call six()
elseif l:x == 7
  call seven()
elseif l:x == 8
  call eight()
else
  call none()
endif

```
With the cursor on any intermediate `elseif` line (say that corresponding to case `4`), try the command `d3i%`. 

### Expected behaviour
```
if l:x == 1
  call one()
elseif l:x == 2
  call two()
elseif l:x == 3
endif
```

4. Observed behavior
```
if l:x == 1
  call one()
elseif l:x == 2
  call two()
elseif l:x == 3
elseif l:x == 4
  call four()
elseif l:x == 5
  call five()
elseif l:x == 6
  call six()
elseif l:x == 7
  call seven()
elseif l:x == 8
  call eight()
else
  call none()
endif
```

However, `d1i%` works correctly as expected, and produces
```
if l:x == 1
endif

```

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The
following should often suffice:

```vim
set nocompatible

" load match-up
let &rtp  = '~/.vim/bundle/vim-matchup,' . &rtp
let &rtp .= ',~/.vim/bundle/vim-matchup/after'

filetype plugin indent on
syntax enable

### Similarly

{count}a% also does not produce expected behaviour.

**Comment by andymass** [comment]
Actually, the intended behavior for `d3i%` is to delete _nothing_.  Counts are supposed to work surrounding:

        [ [ [   cursor   ] ] ]  <-- original
        [ [ [] ] ]              <-- di%
        [ [ [] ] ]              <-- d1i%
        [ [] ]                  <-- d2i%
        []                      <-- d3i%

However the `elseif`s do not surround the cursor's `elseif`, they are on the same level.

`d3i%` is invalid because there are not three enclosing scopes, so the operation is supposed to just fail.  I'll investigate what broke.  Additionally, the readme is wrong in another way because I believe `d2i%` is supposed to delete mid blocks, not just open-close ones (which was the original behavior but got changed).

One option is to allow `di%..` (two dots) to work the way you describe, I notice that could be improved in your example.

**Comment by krishnakumarg1984** [comment]
Ah. Sorry, I didn't quite understand the details in the readme. Thank you for explaining.

**Comment by krishnakumarg1984** [comment]
Thank you very much
