### ISSUE TITLE
[BUG] tag match bug

### ISSUE THREAD

**Issue by iamcco** [andymass/vim-matchup#8]
![image](https://user-images.githubusercontent.com/5492542/33053725-b62d20b4-ce3a-11e7-82e7-3d497b38de31.png)

test example:
```
    <Flex justify="between" style={[tableStyle.mainWrapper, tableStyle.noData]}>
      <FlexItem flex>
        <ActivityIndicator animating size="large"/>
        <Text style={tableStyle.noDataText}>数据加载中。。。</Text>
      </FlexItem>
    </Flex>
```

**Comment by andymass** [comment]
Thanks for the report!   This is actually a problem with vim's html ftplugin (maintained by Dan Sharp) and the same behavior is present in vim's matchit.  I will ask Dan to fix it in the ftplugin.  However, since I think this is a bad bug, I pushed a fix to match-up.  Specifically, I changed the pattern as follows:

before:  `<\@<=\([^/][^ \t>]*\)[^>]*\%(>\|$\):<\@<=/\1>`
after: `<\@<=\([^/][^ \t>]*\)\%(>\|$\|[ \t][^>]*\%(>\|$\)\):<\@<=/\1>`

The "before" pattern does not check for a space after the tag name so `</Flex>` incorrectly matches `<FlexItem>`.

**Comment by iamcco** [comment]
Thanks 👍

**Comment by andymass** [comment]
No problem :)

I noticed in your version of the new regex, you included two `/\@<!`.  What was the reason for this?  Is there an example where that works better?

**Comment by iamcco** [comment]
i was just copy the tail of that regex group of that plugin and add a space，i had think much. but now, i noticed it has some different is:

`<\@<=\([^/][^ \t>]*\)\%(>\|$\|[ \t][^>]*\%(>\|$\)\):<\@<=/\1>` will match
```
<div /> hello world</div>
```
and with `/\@<!` will doesn't
